CREATE SEQUENCE IF NOT EXISTS customers_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS customers (
    id NUMERIC(3) NOT NULL,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100),
    phone VARCHAR(20),
    company VARCHAR(100),
    CONSTRAINT pk_customers PRIMARY KEY (id)
);
