CREATE SEQUENCE CUSTOMERS_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE CUSTOMERS (
    ID NUMBER(3) NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100),
    PHONE VARCHAR2(20),
    COMPANY VARCHAR2(100),
    CONSTRAINT PK_CUSTOMERS PRIMARY KEY (ID)
);
